#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZjFhZjYzZDU1NTk5NWNkMWEyYjhhYmYwNzIxNzVkODZlNDg0NTUwZDRiNGVlNzY4MWFiYTI1MTkyZDlhZGE5NjJlYTcxODcxYzU2NDJiYWJmYTRkODE0NGVjODAwMTEwNWU3Yw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
